-- Phase 2: Property Monitoring Tables
-- Run this in your Supabase SQL Editor

-- 1. listing_snapshots
CREATE TABLE IF NOT EXISTS public.listing_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id BIGINT NOT NULL REFERENCES public.properties(id) ON DELETE CASCADE,
    price VARCHAR,
    status VARCHAR,
    property_data JSONB,
    captured_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    source VARCHAR
);
CREATE INDEX IF NOT EXISTS idx_listing_snapshots_listing_id ON public.listing_snapshots(listing_id);

-- 2. listing_price_history
CREATE TABLE IF NOT EXISTS public.listing_price_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id BIGINT NOT NULL REFERENCES public.properties(id) ON DELETE CASCADE,
    old_price NUMERIC,
    new_price NUMERIC,
    change_amount NUMERIC,
    change_percentage NUMERIC,
    detected_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    source VARCHAR
);
CREATE INDEX IF NOT EXISTS idx_listing_price_history_listing_id ON public.listing_price_history(listing_id);

-- 3. listing_status_history
CREATE TABLE IF NOT EXISTS public.listing_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id BIGINT NOT NULL REFERENCES public.properties(id) ON DELETE CASCADE,
    old_status VARCHAR,
    new_status VARCHAR,
    detected_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    source VARCHAR
);
CREATE INDEX IF NOT EXISTS idx_listing_status_history_listing_id ON public.listing_status_history(listing_id);

-- 4. monitoring_config
CREATE TABLE IF NOT EXISTS public.monitoring_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id BIGINT NOT NULL REFERENCES public.properties(id) ON DELETE CASCADE UNIQUE,
    monitoring_enabled BOOLEAN DEFAULT TRUE,
    monitoring_frequency VARCHAR DEFAULT 'daily',
    last_checked_at TIMESTAMP WITH TIME ZONE,
    next_check_at TIMESTAMP WITH TIME ZONE,
    last_sync_status VARCHAR,
    last_sync_error TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_monitoring_config_listing_id ON public.monitoring_config(listing_id);

-- 5. sync_logs
CREATE TABLE IF NOT EXISTS public.sync_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id BIGINT REFERENCES public.properties(id) ON DELETE CASCADE,
    provider VARCHAR,
    started_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    status VARCHAR,
    error_message TEXT,
    metadata JSONB
);
CREATE INDEX IF NOT EXISTS idx_sync_logs_listing_id ON public.sync_logs(listing_id);
