-- Phase 6: AI Insights Table
-- Run this in your Supabase SQL Editor

CREATE TABLE IF NOT EXISTS public.ai_insights (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id BIGINT REFERENCES public.properties(id) ON DELETE CASCADE,
    suburb VARCHAR,
    insight_type VARCHAR NOT NULL,
    title VARCHAR NOT NULL,
    summary TEXT,
    evidence JSONB,
    confidence NUMERIC,
    source_event_ids JSONB,
    generated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    model VARCHAR
);

CREATE INDEX IF NOT EXISTS idx_ai_insights_listing_id ON public.ai_insights(listing_id);
CREATE INDEX IF NOT EXISTS idx_ai_insights_suburb ON public.ai_insights(suburb);
CREATE INDEX IF NOT EXISTS idx_ai_insights_insight_type ON public.ai_insights(insight_type);
CREATE INDEX IF NOT EXISTS idx_ai_insights_generated_at ON public.ai_insights(generated_at);
