-- Phase 7: Market Alerts Table
-- Run this in your Supabase SQL Editor

CREATE TABLE IF NOT EXISTS public.market_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id BIGINT REFERENCES public.properties(id) ON DELETE CASCADE,
    event_id BIGINT REFERENCES public.market_events(id) ON DELETE CASCADE,
    alert_type VARCHAR NOT NULL,
    severity VARCHAR NOT NULL,
    title VARCHAR NOT NULL,
    message TEXT,
    evidence JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    read_at TIMESTAMP WITH TIME ZONE,
    notification_status VARCHAR DEFAULT 'UNREAD',
    -- Prevent duplicate alerts for the exact same event
    UNIQUE(event_id, alert_type)
);

CREATE INDEX IF NOT EXISTS idx_market_alerts_listing_id ON public.market_alerts(listing_id);
CREATE INDEX IF NOT EXISTS idx_market_alerts_status ON public.market_alerts(notification_status);
CREATE INDEX IF NOT EXISTS idx_market_alerts_created_at ON public.market_alerts(created_at);
