-- Phase 5: Market Events Table
-- Run this in your Supabase SQL Editor

CREATE TABLE IF NOT EXISTS public.market_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id BIGINT NOT NULL REFERENCES public.properties(id) ON DELETE CASCADE,
    event_type VARCHAR NOT NULL,
    old_value VARCHAR,
    new_value VARCHAR,
    metadata JSONB,
    detected_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    source VARCHAR
);

CREATE INDEX IF NOT EXISTS idx_market_events_listing_id ON public.market_events(listing_id);
CREATE INDEX IF NOT EXISTS idx_market_events_event_type ON public.market_events(event_type);
CREATE INDEX IF NOT EXISTS idx_market_events_detected_at ON public.market_events(detected_at);
